apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: monicalopezgris/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: monicalopezgris/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: monicalopezgris/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/*

    # ticketportal.dev
