apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
  - image: monicalopez/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - infra/k8s/*

    # ticketportal.dev